name: master

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.1 ]
        mysql: [ 8.0 ]
        laravel: [ 10.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 10.*
          - testbench: 8.*

    name: P${{ matrix.php }} - M${{ matrix.mysql }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it


      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8mb4_unicode_ci'
          mysql version: ${{ matrix.mysql }}
          mysql database: 'test'
          mysql root password: '123456'
          mysql user: 'user_test'
          mysql password: '123456'

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Problem Matchers
        run: |
            echo "::add-matcher::${{ runner.tool_cache }}/php.json"
            echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Execute Tests
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_HOST: localhost
          DB_USERNAME: user_test
          DB_PASSWORD: "123456"
          DB_DATABASE: test
        run: vendor/bin/phpunit